### ISSUE TITLE
Missing 'tween' module

### ISSUE THREAD

**Issue by macrigiuseppe** [socialtables/react-user-tour#33]
After I installed react-user-tour, i get the following error
```
Error: Cannot find module 'tween'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/giuseppemacri/Documents/projects/avengers/node_modules/react-user-tour/node_modules/scroll-to/index.js:5:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/giuseppemacri/Documents/projects/avengers/node_modules/react-user-tour/dist/helpers/scroll-to-position.js:8:17)
```

**Comment by conorhastings** [comment]
Hi, I'm not sure, seems like it's a dependency of scroll-to module. I tried a fresh install and didn't have any issues, let me know if you can prvoide any more info and i'll reopen
